const PRIVACY_LEVELS = {
  PUBLIC: "PUBLIC",
  FRIENDS_ONLY: "FRIENDS_ONLY",
  PRIVATE: "PRIVATE",
};

const TASK_STATUSES = {
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
};

const ACTIVE_SESSION_STATUSES = {
  RUNNING: "RUNNING",
  PAUSED: "PAUSED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const SESSION_TYPES = {
  POMODORO: "POMODORO",
  STOPWATCH: "STOPWATCH",
};

const XP_PER_MINUTE = 2;
const DAILY_STREAK_MINUTES = 60;
const MAX_SESSION_MINUTES = 240;
const MAX_STOPWATCH_MINUTES = 1440; // 24 hours max
const VERIFICATION_FIRST_CHECK_SECONDS = 14400; // 4 hours
const VERIFICATION_SUBSEQUENT_CHECK_SECONDS = 3600; // 60 minutes
const VERIFICATION_TIMEOUT_SECONDS = 300; // 5 minutes

module.exports = {
  PRIVACY_LEVELS,
  TASK_STATUSES,
  ACTIVE_SESSION_STATUSES,
  SESSION_TYPES,
  XP_PER_MINUTE,
  DAILY_STREAK_MINUTES,
  MAX_SESSION_MINUTES,
  MAX_STOPWATCH_MINUTES,
  VERIFICATION_FIRST_CHECK_SECONDS,
  VERIFICATION_SUBSEQUENT_CHECK_SECONDS,
  VERIFICATION_TIMEOUT_SECONDS,
};
