const PRIVACY_LEVELS = {
  PUBLIC: "PUBLIC",
  FRIENDS_ONLY: "FRIENDS_ONLY",
  PRIVATE: "PRIVATE",
};

const TASK_STATUSES = {
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
};

const ACTIVE_SESSION_STATUSES = {
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const XP_PER_MINUTE = 2;
const DAILY_STREAK_MINUTES = 60;
const MAX_SESSION_MINUTES = 240;

module.exports = {
  PRIVACY_LEVELS,
  TASK_STATUSES,
  ACTIVE_SESSION_STATUSES,
  XP_PER_MINUTE,
  DAILY_STREAK_MINUTES,
  MAX_SESSION_MINUTES,
};
